#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v13
# autospec commit: dc0ff31b4314
#
Name     : rrdtool
Version  : b39df920f0ff31a49460d9872006a2579ee4c7ed
Release  : 40
URL      : https://github.com/oetiker/rrdtool-1.x/archive/b39df920f0ff31a49460d9872006a2579ee4c7ed.tar.gz
Source0  : https://github.com/oetiker/rrdtool-1.x/archive/b39df920f0ff31a49460d9872006a2579ee4c7ed.tar.gz
Summary  : Round Robin Database Tool to store and display time-series data
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ LGPL-2.1
Requires: rrdtool-bin = %{version}-%{release}
Requires: rrdtool-data = %{version}-%{release}
Requires: rrdtool-lib = %{version}-%{release}
Requires: rrdtool-license = %{version}-%{release}
Requires: rrdtool-locales = %{version}-%{release}
Requires: rrdtool-man = %{version}-%{release}
Requires: rrdtool-perl = %{version}-%{release}
Requires: rrdtool-python = %{version}-%{release}
Requires: rrdtool-python3 = %{version}-%{release}
BuildRequires : bc
BuildRequires : file
BuildRequires : glib-dev
BuildRequires : groff
BuildRequires : lua-dev
BuildRequires : pcre-dev
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : python3-dev
BuildRequires : ruby
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Save-value-specified-by-enable-perl-site-install.patch

%description
RRD is the Acronym for Round Robin Database. RRD is a system to store and
display time-series data (i.e. network bandwidth, machine-room temperature,
server load average). It stores the data in a very compact way that will not
expand over time, and it presents useful graphs by processing the data to
enforce a certain data density. It can be used either via simple wrapper
scripts (from shell or Perl) or via frontends that poll network devices and
put a friendly user interface on it.

%package bin
Summary: bin components for the rrdtool package.
Group: Binaries
Requires: rrdtool-data = %{version}-%{release}
Requires: rrdtool-license = %{version}-%{release}

%description bin
bin components for the rrdtool package.


%package data
Summary: data components for the rrdtool package.
Group: Data

%description data
data components for the rrdtool package.


%package dev
Summary: dev components for the rrdtool package.
Group: Development
Requires: rrdtool-lib = %{version}-%{release}
Requires: rrdtool-bin = %{version}-%{release}
Requires: rrdtool-data = %{version}-%{release}
Provides: rrdtool-devel = %{version}-%{release}
Requires: rrdtool = %{version}-%{release}

%description dev
dev components for the rrdtool package.


%package doc
Summary: doc components for the rrdtool package.
Group: Documentation
Requires: rrdtool-man = %{version}-%{release}

%description doc
doc components for the rrdtool package.


%package lib
Summary: lib components for the rrdtool package.
Group: Libraries
Requires: rrdtool-data = %{version}-%{release}
Requires: rrdtool-license = %{version}-%{release}

%description lib
lib components for the rrdtool package.


%package license
Summary: license components for the rrdtool package.
Group: Default

%description license
license components for the rrdtool package.


%package locales
Summary: locales components for the rrdtool package.
Group: Default

%description locales
locales components for the rrdtool package.


%package man
Summary: man components for the rrdtool package.
Group: Default

%description man
man components for the rrdtool package.


%package perl
Summary: perl components for the rrdtool package.
Group: Default
Requires: rrdtool = %{version}-%{release}

%description perl
perl components for the rrdtool package.


%package python
Summary: python components for the rrdtool package.
Group: Default
Requires: rrdtool-python3 = %{version}-%{release}

%description python
python components for the rrdtool package.


%package python3
Summary: python3 components for the rrdtool package.
Group: Default
Requires: python3-core

%description python3
python3 components for the rrdtool package.


%prep
%setup -q -n rrdtool-1.x-b39df920f0ff31a49460d9872006a2579ee4c7ed
cd %{_builddir}/rrdtool-1.x-b39df920f0ff31a49460d9872006a2579ee4c7ed
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719871627
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static --enable-perl-site-install="PREFIX=/usr INSTALL_BASE= LIB=$(perl -V::installvendorlib: | sed "s|'\(.*\)'|\1|")"
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1719871627
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rrdtool
cp %{_builddir}/rrdtool-1.x-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/rrdtool/db95910cb27890d60e596e4c622fc3eeba6693fa || :
cp %{_builddir}/rrdtool-1.x-%{version}/bindings/python/COPYING %{buildroot}/usr/share/package-licenses/rrdtool/9a647436aa2324c4cb849c6f3d31c392ed50d9bd || :
export GOAMD64=v2
GOAMD64=v2
%make_install
%find_lang rrdtool
## install_append content
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -type f -name perllocal.pod -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rrdcached
/usr/bin/rrdcgi
/usr/bin/rrdcreate
/usr/bin/rrdinfo
/usr/bin/rrdtool
/usr/bin/rrdupdate

%files data
%defattr(-,root,root,-)
/usr/share/rrdtool/examples/4charts.pl
/usr/share/rrdtool/examples/bigtops.pl
/usr/share/rrdtool/examples/cgi-demo.cgi
/usr/share/rrdtool/examples/minmax.pl
/usr/share/rrdtool/examples/perftest.pl
/usr/share/rrdtool/examples/piped-demo.pl
/usr/share/rrdtool/examples/rrdcached/RRDCached.pm
/usr/share/rrdtool/examples/rrdcached/rrdcached-size.pl
/usr/share/rrdtool/examples/shared-demo.pl
/usr/share/rrdtool/examples/stripes.pl
/usr/share/rrdtool/examples/stripes.py

%files dev
%defattr(-,root,root,-)
/usr/include/rrd.h
/usr/include/rrd_client.h
/usr/include/rrd_format.h
/usr/lib64/librrd.so
/usr/lib64/pkgconfig/librrd.pc
/usr/share/man/man3/RRDp.3
/usr/share/man/man3/RRDs.3
/usr/share/man/man3/librrd.3

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/rrdtool-1.8.0/html/RRDp.html
/usr/share/doc/rrdtool-1.8.0/html/RRDs.html
/usr/share/doc/rrdtool-1.8.0/html/bin_dec_hex.html
/usr/share/doc/rrdtool-1.8.0/html/cdeftutorial.html
/usr/share/doc/rrdtool-1.8.0/html/index.html
/usr/share/doc/rrdtool-1.8.0/html/librrd.html
/usr/share/doc/rrdtool-1.8.0/html/rpntutorial.html
/usr/share/doc/rrdtool-1.8.0/html/rrd-beginners.html
/usr/share/doc/rrdtool-1.8.0/html/rrd_pdpcalc.html
/usr/share/doc/rrdtool-1.8.0/html/rrdbuild.html
/usr/share/doc/rrdtool-1.8.0/html/rrdcached.html
/usr/share/doc/rrdtool-1.8.0/html/rrdcgi.html
/usr/share/doc/rrdtool-1.8.0/html/rrdcreate.html
/usr/share/doc/rrdtool-1.8.0/html/rrddump.html
/usr/share/doc/rrdtool-1.8.0/html/rrdfetch.html
/usr/share/doc/rrdtool-1.8.0/html/rrdfirst.html
/usr/share/doc/rrdtool-1.8.0/html/rrdflushcached.html
/usr/share/doc/rrdtool-1.8.0/html/rrdgraph.html
/usr/share/doc/rrdtool-1.8.0/html/rrdgraph_data.html
/usr/share/doc/rrdtool-1.8.0/html/rrdgraph_examples.html
/usr/share/doc/rrdtool-1.8.0/html/rrdgraph_graph.html
/usr/share/doc/rrdtool-1.8.0/html/rrdgraph_rpn.html
/usr/share/doc/rrdtool-1.8.0/html/rrdinfo.html
/usr/share/doc/rrdtool-1.8.0/html/rrdlast.html
/usr/share/doc/rrdtool-1.8.0/html/rrdlastupdate.html
/usr/share/doc/rrdtool-1.8.0/html/rrdlist.html
/usr/share/doc/rrdtool-1.8.0/html/rrdlua.html
/usr/share/doc/rrdtool-1.8.0/html/rrdpython.html
/usr/share/doc/rrdtool-1.8.0/html/rrdresize.html
/usr/share/doc/rrdtool-1.8.0/html/rrdrestore.html
/usr/share/doc/rrdtool-1.8.0/html/rrdruby.html
/usr/share/doc/rrdtool-1.8.0/html/rrdthreads.html
/usr/share/doc/rrdtool-1.8.0/html/rrdtool.html
/usr/share/doc/rrdtool-1.8.0/html/rrdtune.html
/usr/share/doc/rrdtool-1.8.0/html/rrdtutorial.html
/usr/share/doc/rrdtool-1.8.0/html/rrdupdate.html
/usr/share/doc/rrdtool-1.8.0/html/rrdxport.html
/usr/share/doc/rrdtool-1.8.0/txt/bin_dec_hex.pod
/usr/share/doc/rrdtool-1.8.0/txt/bin_dec_hex.txt
/usr/share/doc/rrdtool-1.8.0/txt/cdeftutorial.pod
/usr/share/doc/rrdtool-1.8.0/txt/cdeftutorial.txt
/usr/share/doc/rrdtool-1.8.0/txt/librrd.txt
/usr/share/doc/rrdtool-1.8.0/txt/rpntutorial.pod
/usr/share/doc/rrdtool-1.8.0/txt/rpntutorial.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrd-beginners.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrd-beginners.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrd_pdpcalc.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrd_pdpcalc.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdbuild.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdbuild.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdcached.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdcached.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdcgi.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdcgi.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdcreate.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdcreate.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrddump.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrddump.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdfetch.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdfetch.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdfirst.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdfirst.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdflushcached.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdflushcached.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdgraph.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdgraph.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdgraph_data.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdgraph_data.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdgraph_examples.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdgraph_examples.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdgraph_graph.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdgraph_graph.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdgraph_rpn.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdgraph_rpn.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdinfo.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdinfo.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdlast.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdlast.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdlastupdate.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdlastupdate.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdlist.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdlist.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdlua.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdlua.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdpython.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdpython.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdresize.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdresize.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdrestore.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdrestore.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdruby.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdruby.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdthreads.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdthreads.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdtool.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdtool.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdtune.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdtune.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdtutorial.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdtutorial.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdupdate.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdupdate.txt
/usr/share/doc/rrdtool-1.8.0/txt/rrdxport.pod
/usr/share/doc/rrdtool-1.8.0/txt/rrdxport.txt

%files lib
%defattr(-,root,root,-)
/usr/lib64/librrd.so.8
/usr/lib64/librrd.so.8.3.0
/usr/lib64/lua/5.4/rrd.so
/usr/lib64/lua/5.4/rrd.so.0
/usr/lib64/lua/5.4/rrd.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rrdtool/9a647436aa2324c4cb849c6f3d31c392ed50d9bd
/usr/share/package-licenses/rrdtool/db95910cb27890d60e596e4c622fc3eeba6693fa

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bin_dec_hex.1
/usr/share/man/man1/cdeftutorial.1
/usr/share/man/man1/rpntutorial.1
/usr/share/man/man1/rrd-beginners.1
/usr/share/man/man1/rrd_pdpcalc.1
/usr/share/man/man1/rrdbuild.1
/usr/share/man/man1/rrdcached.1
/usr/share/man/man1/rrdcgi.1
/usr/share/man/man1/rrdcreate.1
/usr/share/man/man1/rrddump.1
/usr/share/man/man1/rrdfetch.1
/usr/share/man/man1/rrdfirst.1
/usr/share/man/man1/rrdflushcached.1
/usr/share/man/man1/rrdgraph.1
/usr/share/man/man1/rrdgraph_data.1
/usr/share/man/man1/rrdgraph_examples.1
/usr/share/man/man1/rrdgraph_graph.1
/usr/share/man/man1/rrdgraph_rpn.1
/usr/share/man/man1/rrdinfo.1
/usr/share/man/man1/rrdlast.1
/usr/share/man/man1/rrdlastupdate.1
/usr/share/man/man1/rrdlist.1
/usr/share/man/man1/rrdlua.1
/usr/share/man/man1/rrdpython.1
/usr/share/man/man1/rrdresize.1
/usr/share/man/man1/rrdrestore.1
/usr/share/man/man1/rrdruby.1
/usr/share/man/man1/rrdthreads.1
/usr/share/man/man1/rrdtool.1
/usr/share/man/man1/rrdtune.1
/usr/share/man/man1/rrdtutorial.1
/usr/share/man/man1/rrdupdate.1
/usr/share/man/man1/rrdxport.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f rrdtool.lang
%defattr(-,root,root,-)

